language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
install:
  - composer install --no-dev --prefer-source --no-interaction
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}

env:
  - PHPUNIT_VERSION="5.4.*"
  - PHPUNIT_VERSION="4.8"

script: vendor/bin/phpunit
